# Project
version=1.0.2
group=einstein.fire_pots
java_version=21

# Common
minecraft_version=1.21.6
max_minecraft_version=1.21.8
neo_form_version=1.21.6-20250617.151856
parchment_minecraft_version=1.21.5
parchment_version=2025.06.15

# Fabric
fabric_version=0.16.14
fabric_api_version=0.127.1+1.21.6

# NeoForge
neoforge_version=21.6.5-beta
neoforge_loader_version_range=[4,)

# Mod options
mod_name=FiredPots
mod_author=MincraftEinstein
mod_id=fired_pots
description=Decorated pots are now crafted by firing a clay pot, just like it was shown at Minecraft Live 2020

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
