# Project
version=1.0.2
group=einstein.fire_pots
java_version=21

# Common
minecraft_version=1.21.5
max_minecraft_version=1.21.6
neo_form_version=1.21.5-20250325.162830
parchment_minecraft_version=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.16.10
fabric_api_version=0.119.5+1.21.5

# NeoForge
neoforge_version=21.5.0-beta
neoforge_loader_version_range=[4,)

# Mod options
mod_name=FiredPots
mod_author=MincraftEinstein
mod_id=fired_pots
description=Decorated pots are now crafted by firing a clay pot, just like it was shown at Minecraft Live 2020

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
