@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.fired_pots.client.renderers.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
